version: '3.8'

services:
  php:
    build: .
    container_name: wackopicko-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=wackopicko
      - MYSQL_PASSWORD=wackopicko
      - MYSQL_DATABASE=wackopicko

  db:
    image: mysql:5.7
    container_name: wackopicko-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wackopicko
      MYSQL_USER: wackopicko
      MYSQL_PASSWORD: wackopicko
    volumes:
      - ./current.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
